spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:cobedt123@gmail.com}
    password: ${EMAIL_PASSWORD:czkxbisyxmgfjknz}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
    test-connection: false
    protocol: smtp
deliverableMail:
  api_key: ${DELIVERABLE_MAIL_API_KEY:2359fee504724cb3b2f46ff7d3390c1a}
